name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history
          lfs: true

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Authenticate and Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/melbournelopes/File_Assistant || true
          git fetch hf main
          git merge --strategy-option=theirs hf/main || true
          git push hf main
